name: PUBLISH

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Perform a dry run (build without publishing)'
        type: boolean
        default: false

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  publish:
    name: Build and Publish Python Project
    uses: ./.github/workflows/reusable-python.yml
    with:
      working_directory: src
      publish: true
      dry_run: ${{ inputs.dry_run }}
    secrets:
      PYPI_PAT: ${{ secrets.PYPI_PAT }}
