name: VALIDATE PR

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  validate:
    name: Validate Python Project
    uses: ./.github/workflows/reusable-python.yml
    with:
      working_directory: .

    